version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
