version: '3'
services:
  node:
    build: .
    ports: "8080:8080"
    depends_on:
      - mysql
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  volumes:
    postgres-data:
